# Generated by Django 3.0.3 on 2020-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customernumber', models.CharField(db_column='CustomerNumber', max_length=10, unique=True)),
                ('nationalid', models.IntegerField(db_column='NationalID')),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=100)),
                ('fathersname', models.CharField(blank=True, db_column='FathersName', max_length=50, null=True)),
                ('bankaccount', models.CharField(blank=True, db_column='BankAccount', max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=15, null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=15, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loadings',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('invoicenumber', models.CharField(db_column='InvoiceNumber', max_length=10, unique=True)),
                ('loaddate', models.DateTimeField(db_column='LoadDate')),
                ('loaddateshamsi', models.CharField(db_column='LoadDateShamsi', max_length=20)),
                ('driver', models.CharField(blank=True, db_column='Driver', max_length=50, null=True)),
                ('vehiclenumber', models.CharField(blank=True, db_column='VehicleNumber', max_length=15, null=True)),
                ('customerid', models.CharField(db_column='CustomerID', max_length=10)),
                ('waybill', models.CharField(blank=True, db_column='Waybill', max_length=20, null=True)),
                ('loadedweight', models.DecimalField(blank=True, db_column='LoadedWeight', decimal_places=0, max_digits=18, null=True)),
                ('unloadedweight', models.DecimalField(blank=True, db_column='UnloadedWeight', decimal_places=0, max_digits=18, null=True)),
                ('pureweight', models.DecimalField(blank=True, db_column='PureWeight', decimal_places=0, max_digits=18, null=True)),
                ('invoicetype', models.CharField(blank=True, db_column='InvoiceType', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'Loadings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loadtypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'LoadTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempLoadings',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('invoicenumber', models.CharField(db_column='InvoiceNumber', max_length=10)),
                ('loaddate', models.DateTimeField(db_column='LoadDate')),
                ('loaddateshamsi', models.CharField(db_column='LoadDateShamsi', max_length=20)),
                ('driver', models.CharField(blank=True, db_column='Driver', max_length=50, null=True)),
                ('vehiclenumber', models.CharField(blank=True, db_column='VehicleNumber', max_length=15, null=True)),
                ('customerid', models.CharField(db_column='CustomerID', max_length=10)),
                ('waybill', models.CharField(blank=True, db_column='Waybill', max_length=20, null=True)),
                ('loadedweight', models.DecimalField(blank=True, db_column='LoadedWeight', decimal_places=0, max_digits=18, null=True)),
                ('unloadedweight', models.DecimalField(blank=True, db_column='UnloadedWeight', decimal_places=0, max_digits=18, null=True)),
                ('pureweight', models.DecimalField(blank=True, db_column='PureWeight', decimal_places=0, max_digits=18, null=True)),
                ('invoicetype', models.CharField(blank=True, db_column='InvoiceType', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'temp_loadings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiclestype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'VehiclesType',
                'managed': False,
            },
        ),
    ]
